server:
  servlet:
    encoding:
      force-response: true
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    show-sql: true
    database-platform:
    database:
    hibernate.ddl-auto: update

